# Generated by Django 5.2.17 on 2026-09-08 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reassignment', 'Approved reassignment'), ('override', 'Organizer override')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_audits', to=settings.AUTH_USER_MODEL)),
                ('new_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='chores.childprofile')),
                ('new_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_audits', to='chores.occurrence')),
                ('previous_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='chores.childprofile')),
                ('previous_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('assignment', 'Weekly assignment'), ('reminder', 'Due-day reminder')], max_length=12)),
                ('recipient', models.EmailField(max_length=254)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='chores.household')),
                ('occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='chores.occurrence')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('allocate', 'Allocate week'), ('remind', 'Send due-day reminders'), ('overdue', 'Mark overdue')], max_length=12)),
                ('run_at', models.DateTimeField()),
                ('target_date', models.DateField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to='chores.household')),
            ],
        ),
        migrations.CreateModel(
            name='FairnessSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('capacity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=8)),
                ('base_target_minutes', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adjusted_target_minutes', models.DecimalField(decimal_places=2, max_digits=8)),
                ('assigned_minutes', models.PositiveIntegerField(default=0)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fairness', to='chores.childprofile')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fairness_summaries', to='chores.household')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fairness', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('child__isnull', True), ('user__isnull', False)), models.Q(('child__isnull', False), ('user__isnull', True)), _connector='OR'), name='fairness_has_exactly_one_member'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('week_start', 'user'), name='one_fairness_summary_per_adult_week'), models.UniqueConstraint(condition=models.Q(('child__isnull', False)), fields=('week_start', 'child'), name='one_fairness_summary_per_child_week')],
            },
        ),
        migrations.CreateModel(
            name='ReassignmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=280)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reassignment_decisions', to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignment_requests', to='chores.occurrence')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reassignment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('occurrence',), name='one_pending_reassignment_per_occurrence')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='chores.childprofile')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_capacities', to='chores.household')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('child__isnull', True), ('user__isnull', False)), models.Q(('child__isnull', False), ('user__isnull', True)), _connector='OR'), name='capacity_has_exactly_one_member'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('week_start', 'user'), name='one_capacity_per_adult_week'), models.UniqueConstraint(condition=models.Q(('child__isnull', False)), fields=('week_start', 'child'), name='one_capacity_per_child_week')],
            },
        ),
    ]
